version: "3.4"

volumes:
  conandata:
  builddata:

services:
  backend:
    image: qchateau/space-dodgems:dev
    build:
      target: dev
    volumes:
      - ./server/:/opt/server/
      - conandata:/root/.conan/
      - builddata:/opt/server/build/
