version: "3.4"

volumes:
  conandata:
  builddata:

services:
  nginx:
    restart: always
    image: nginx:1.19
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./client:/www/data
    ports:
      - "${EXTERNAL_PORT-8080}:80"
    environment:
      - WS_SERVER=backend:5678

  backend:
    restart: always
    image: qchateau/space-dodgems:latest
    build:
      context: ./server
      target: release
    environment:
      - ADDR=0.0.0.0
      - PORT=5678
      - NWORLDS=${NWORLDS-10}
