version: "3.2"

volumes:
  conandata:

services:
  nginx:
    restart: always
    image: nginx:1.19
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./client:/www/data
    ports:
      - "8080:80"
    environment:
      - WS_SERVER=backend:5678

  backend:
    restart: always
    build:
      context: ./server
    volumes:
      - conandata:/root/.conan/
      - ./server/:/opt/server/
    environment:
      - BIND_IP=0.0.0.0
      - PORT=5678
