version: "3.2"

services:
  nginx:
    restart: always
    image: nginx:1.19
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./client:/www/data
    ports:
      - "8080:80"
    environment:
      - WS_SERVER=ws_backend:5678

  ws_backend:
    restart: always
    image: alpine:3.12
    volumes:
      - ./server/build/bin:/server/
    command: /server/server 0.0.0.0 5678
